_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("F:\\data\\detectron2_mask_rcnn\\annotations\\3.json","F:\\data\\detectron2_mask_rcnn\\images\\",)
  TEST: ("coco_2017_val",)
SOLVER:
  STEPS: (10000,14000,18000,)
  MAX_ITER: 20000
  WARMUP_ITERS: 4000
  WARMUP_FACTOR: 0.001
VERSION: 2
