_BASE_: "../Centernet-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "F:\\data\\faster_rcnn\\weight\\epoch_3300.pt"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.25
    NMS_THRESH_TEST: 0.45
DATASETS:
  #TRAIN: ("F:\\data\\detectron2_mask_rcnn\\annotations\\4.json","F:\\data\\detectron2_mask_rcnn\\images\\",)
  TRAIN: ("F:\\data\\faster_rcnn\\annotations\\train.json","F:\\data\\faster_rcnn\\images\\train\\",)
  TEST: ("coco_2017_val",)
SOLVER:
  STEPS: (15000,20000,30000,)
  MAX_ITER: 40000
  WARMUP_ITERS: 4000
  WARMUP_FACTOR: 0.00025
VERSION: 2
